export const Users = [
  {
    id: 1,
    profilePicture: "assets/basketballplayer1.jpg",
    username: "Joe Beal",
  },
  {
    id: 2,
    profilePicture: "assets/baseballplayer1.jpg",
    username: "John Hand",
  },
  {
    id: 3,
    profilePicture: "assets/hockeyplayer1.jpg",
    username: "Rebecca Lidge",
  },
  {
    id: 4,
    profilePicture: "assets/footballplayer1.jpg",
    username: "Brock O'Neal",
  },
  {
    id: 5,
    profilePicture: "assets/footballplayer2.jpg",
    username: "Brandon Jones",
  },
  {
    id: 6,
    profilePicture: "assets/soccerplayer1.jpg",
    username: "Kendrick Odom",
  },
  {
    id: 7,
    profilePicture: "assets/soccerplayer2.jpg",
    username: "Patrick Thompson",
  },
  {
    id: 8,
    profilePicture: "assets/soccerplayer3.jpg",
    username: "Jill Oaks",
  },
  {
    id: 9,
    profilePicture: "assets/tennisplayer1.jpg",
    username: "Hillary Swan",
  },
  {
    id: 10,
    profilePicture: "assets/basketballplayer2.jpg",
    username: "Jack Bradford",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Look at how sick these courts are!",
    photo: "assets/post1.jpg",
    date: "10 days ago",
    userId: 1,
    like: 50,
    comment: 7,
  },
  {
    id: 2,
    desc: "At the beach field today!",
    photo: "assets/post2.jpg",
    date: "20 days ago",
    userId: 2,
    like: 80,
    comment: 17,
  },
  {
    id: 3,
    desc: "Brand new basketball!",
    photo: "assets/post3.jpg",
    date: "12 days ago",
    userId: 3,
    like: 53,
    comment: 57,
  },
  {
    id: 4,
    desc: "Flying to my next game!",
    photo: "assets/post4.jpg",
    date: "45 days ago",
    userId: 4,
    like: 4,
    comment: 2,
  },
  {
    id: 5,
    desc: "Final score from today's game!",
    photo: "assets/post5.jpg",
    date: "2 months ago",
    userId: 5,
    like: 52,
    comment: 9,
  },
  {
    id: 6,
    desc: "Brand new ice rink downtown!",
    photo: "assets/post6.jpg",
    date: "10 days ago",
    userId: 6,
    like: 55,
    comment: 47,
  },
  {
    id: 7,
    desc: "Which one should I get?",
    photo: "assets/post7.jpg",
    date: "6 days ago",
    userId: 7,
    like: 500,
    comment: 67,
  },
  {
    id: 8,
    desc: "Remember to stay hydrated!",
    photo: "assets/post8.jpg",
    date: "1 day ago",
    userId: 8,
    like: 67,
    comment: 4,
  },
  {
    id: 9,
    desc: "My brand new running shoes!",
    photo: "assets/post9.jpg",
    date: "27 days ago",
    userId: 9,
    like: 68,
    comment: 4,
  },
  {
    id: 10,
    desc: "The lights are bright on this field!",
    photo: "assets/post10.jpg",
    date: "3 days ago",
    userId: 10,
    like: 504,
    comment: 57,
  },
];
